### ISSUE TITLE
[Bug]: build.sh failed

### ISSUE THREAD

**Issue by plmqwsa** [oceanbase/oceanbase-diagnostic-tool#13]
### Check Before Asking

- [X] Please check the issue list and confirm this bug is encountered for the first time.
- [X] Please try full text in English and attach precise description.

### Fast Reproduce Steps

command "cd oceanbase-diagnostic-tool && sh ./build/build.sh" failed

### Actual Behavior

command "cd oceanbase-diagnostic-tool && sh ./build/build.sh" failed

**Comment by Teingi** [comment]
fixed. commit: https://github.com/oceanbase/oceanbase-diagnostic-tool/commit/1407153f2772cd79d3fda515ae849339be4658c0
