### ISSUE TITLE
[Feat.]: Whether it can support without filling in the host login user name and password

### ISSUE THREAD

**Issue by plmqwsa** [oceanbase/oceanbase-diagnostic-tool#14]
### Check Before Asking

- [X] Please check the issue list and confirm this feature is encountered for the first time.
- [X] Please try full text in English and attach precise description.

### Description

```markdown
The host has been set up for mutual trust and confidentiality. Whether it can support without filling in the host login user name and password.
```

**Comment by Teingi** [comment]
Okay, good suggestion.

**Comment by Teingi** [comment]
This feature is already supported
