### ISSUE TITLE
[Enhancement]: 集群节点比较多时，sql_result.txt输出结果文件过大

### ISSUE THREAD

**Issue by mycms5** [oceanbase/oceanbase-diagnostic-tool#149]
### Description

集群节点比较多时，使用自定义yaml文件，查询的信息比较多，sql_result.txt输出结果文件过大，过2G。
建议按指定大小，分文件输出，谢谢！

**Comment by Teingi** [comment]
![image](https://github.com/oceanbase/oceanbase-diagnostic-tool/assets/35712518/6215bf0e-fc9d-4636-ada8-2003eea430f7)
