### ISSUE TITLE
[Feat.]: Community OCP 4.0.0 does not support awr report, Is this tool unable to gather awr reports.

### ISSUE THREAD

**Issue by plmqwsa** [oceanbase/oceanbase-diagnostic-tool#16]
### Check Before Asking

- [X] Please check the issue list and confirm this feature is encountered for the first time.
- [X] Please try full text in English and attach precise description.

### Description

```markdown
I noticed that your tool relies on ocp to gather AWR reports. But OCP community 4.0.0 does not support awr report, is this tool unable to gather awr reports?
```

**Comment by Teingi** [comment]
yes, AWR reports relies on ocp.
