### ISSUE TITLE
[Feature]: 使用阵列卡设置写入规则为Write back时Clog合并异常

### ISSUE THREAD

**Issue by uouuou** [oceanbase/oceanbase-diagnostic-tool#69]
### Describe your use case

在设备迁移到使用Write back设置的阵列卡SSD是INTEL SSDSC2BB01的时候会导致OB 4.1.0.1的clog回放异常，导致所有节点日志同步不正常，导致节点的合并异常，导致节点的备份异常，导致节点无法操作

### Describe the solution you'd like

目前来看只能是模拟消费来测试是否存在问题，有问题就提示用户修订为直写或者修改为JOB存储

**Comment by uouuou** [comment]
希望obdiag 支持该种问题的检测和提前预警以及相关问题处理办法的指引

**Comment by Teingi** [comment]
很好的建议，我们会尽快在后面的迭代支持这种场景的诊断。
